sonar.projectKey=bckirkup_Coral_Key_in_Three_Hour_Epochs
sonar.organization=bckirkup
sonar.sources=src,scripts,baselines
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
